server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2147483648
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sisp.demoproject.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true

